### ISSUE TITLE
[Bug] A typo in Book 1

### ISSUE THREAD

**Issue by rongguodong** [RayTracing/raytracing.github.io#714] opened 2020-08-27 21:01 UTC
There is a tiny typo in "Listing 65":
![image](https://user-images.githubusercontent.com/11858549/91494552-db818800-e86d-11ea-9df1-5d366747f072.png)

Here you just want to change FOV from 90 to 20. So you should keep the up-vector as before, i.e. vec3(0,1,0). "vup" is not declared in main.cc. So this line will cause an "undeclared identifier" error.

**Comment by hollasch** [comment] 2020-08-27 23:50
Duplicate of #686

**Closed by hollasch** 2020-08-27 23:50 UTC
