### ISSUE TITLE
[Book 2][ver Version 4.0.0-alpha.1][4.2 Solid Textures: A Checker Texture}

### ISSUE THREAD

**Issue by Imasu** [RayTracing/raytracing.github.io#1397] opened 2024-02-21 23:20 UTC
Hello,

As always, thank you for writing these books.

I was able to follow the Book 2 up to chapter 4.2 without too much trouble ( I use C# to code).
However, chapter 4.2 is missing a description for updating the Lambertian material with the new texture (including a new constructor and an update of the albedo from color to solid_color texture). It is just for a better understanding of the reader as the code itself is correct.

Here are the changes:

```
class lambertian : public material {
  public:
    lambertian(const color& a) : albedo(make_shared<solid_color>(a)) {}
    lambertian(shared_ptr<texture> a) : albedo(a) {}

    bool scatter(const ray& r_in, const hit_record& rec, color& attenuation, ray& scattered)  const override {
      [...]
      attenuation = albedo->value(rec.u, rec.v, rec.p);
      [...]
    }

  private:
    _shared_ptr<texture> albedo;_
}
```

Additionnaly, this chapter indicates changes to the "random_scene()" method, but that method has not been introduced yet ; it is covered in chapter 4.3.

I hope this help!

**Comment by hollasch** [comment] 2024-02-22 01:32
Thanks for the report!

**Comment by harrism76** [comment] 2024-03-10 13:40
Thank you for books, good thing the source is updated, the book second week doesn't mention updating material the lambertian portion. VS2019 error pointing to some xutility.h file, must be a windows header. Updated the code and the checker patterns worked. I'm using c++, for anyone searching for xutility.h error
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'lambertian::lambertian(std::shared_ptr<texture>)': cannot convert argument 1 from 'color' to 'std::shared_ptr<texture>'	RayTracer_week2	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xutility	149

**Comment by hollasch** [comment] 2024-03-10 18:25
Duplicate of #1258.
PR #1275.
Fixed in `dev`.

**Closed as completed by hollasch** 2024-03-10 18:25 UTC
Labels: resolved: duplicate
