### ISSUE TITLE
[BOOK 1] Section 4.2  Typos in integer_height and image height

### ISSUE THREAD

**Issue by ThePlatypusEveryoneLoves** [RayTracing/raytracing.github.io#1342] opened 2023-12-08 04:28 UTC
Both the `image_height` and the `integer_height` are used interchangeably in section 4.2 when `image_height` is used in the code:
>
> ```cpp
> auto aspect_ratio = 16.0 / 9.0;
> int image_width = 400;
> 
> // Calculate the image height, and ensure that it's at least 1.
> int image_height = static_cast<int>(image_width / aspect_ratio);
> image_height = (image_height < 1) ? 1 : image_height;
> 
> // Viewport widths less than one are ok since they are real valued.
> auto viewport_height = 2.0;
> auto viewport_width = viewport_height * (static_cast<double>(image_width)/image_height);
> ```
> # Listing 8: Rendered image setup
> 
> If you're wondering why we don't just use aspect_ratio when computing viewport_width, it's because the value set to aspect_ratio is the ideal ratio, it may not be the actual ratio between `image_width` and `image_height`. If `image_height` was allowed to be real valued—rather than just an integer—then it would fine to use aspect_ratio. But the actual ratio between image_width and image_height can vary based on two parts of the code. First, `integer_height` is rounded down to the nearest integer, which can increase the ratio. Second, we don't allow `integer_height` to be less than one, which can also change the actual aspect ratio.

**Comment by dimitry-ishenko** [comment] 2024-01-24 01:36
Hmm... @hollasch you've marked this as fixed in #1246

**Comment by dimitry-ishenko** [comment] 2024-01-24 01:43
And, since we are on the subject:

![Screenshot from 2024-01-23 20-28-24](https://github.com/RayTracing/raytracing.github.io/assets/2858291/5341097a-13f7-43fc-8d91-c26716c7e68a)

**Comment by hollasch** [comment] 2024-01-24 02:38
Yes, duplicate of #1246.

Also, the missing word "be" above is also fixed in `dev`.

**Closed as completed by hollasch** 2024-01-24 02:38 UTC
