### ISSUE TITLE
Portable random number generation

### ISSUE THREAD

**Issue by ronaldfw** [RayTracing/raytracing.github.io#99] opened 2019-08-23 17:31 UTC
Mirror changes in https://github.com/RayTracing/InOneWeekend/pull/74

This should boil down to:
1) Add same random.h file from the src code of the first book.
2) Replace drand48() with random_double() everywhere.

**Comment by hollasch** [comment] 2019-08-30 23:17
Now duplicate of #70

**Closed by hollasch** 2019-08-30 23:17 UTC
Labels: TheNextWeek, book, code
