### ISSUE TITLE
Book 3.3.4: Importance Sampling: Error in inverse of `P(x)`

### ISSUE THREAD

**Issue by zmill** [RayTracing/raytracing.github.io#1027] opened 2022-06-12 19:42 UTC
In the prose for this section, the coefficient in the inverse of `P(x)` should be `2`, or else the `8x` should be in parentheses so the exponent applies to both.

The code in Listing 7 is correct, although it looks like in the corresponding listing in the dev-major branch (15? It's `Listing [integ-xsq-5]`), the 8 has been incorrectly factored out of the cube root to match the prose.

The coefficient doesn't affect the result since it cancels out anyway, but it threw me for a loop reading through the first time.

**Comment by dimitry-ishenko** [comment] 2024-04-25 21:30
This might be a duplicate of #1310?

**Comment by hollasch** [comment] 2024-04-26 01:04
Yes, duplicate of #1310.

**Closed by hollasch** 2024-04-26 01:04 UTC
Labels: book 3: Your Life, level: patch, resolved: duplicate
