### ISSUE TITLE
[Book 1] Variable vup is undefined in Listing 65

### ISSUE THREAD

**Issue by jagu2012** [RayTracing/raytracing.github.io#743] opened 2020-10-01 02:32 UTC
Hi, in Listing 65 a camera is constructed with a parameter 'vup', but vup isn't instantiated until later in Listing 68.

https://github.com/RayTracing/raytracing.github.io/blob/7b92650a045a887391bf8148af86c5e6c46c7a9e/books/RayTracingInOneWeekend.html#L2850

https://github.com/RayTracing/raytracing.github.io/blob/7b92650a045a887391bf8148af86c5e6c46c7a9e/books/RayTracingInOneWeekend.html#L2996

As best as I can see, this section was previously just an asside saying "And we can change field of view to get..." and later the code listing was added by way of example. But the example was created from the later listing code which had vup.

I think the solution *is not* to instantiate vup, but rather to use the same value *vec3(0,1,0)* from the immediately previous Listing 64. Vup makes more sense being created in Listing 68 as it is now.

I'll submit a pull fix shortly.

**Comment by hollasch** [comment] 2020-10-01 02:33
Duplicate of #686.

**Closed by hollasch** 2020-10-01 02:33 UTC

**Comment by jagu2012** [comment] 2020-10-01 02:36
Forgive me this is a duplicate of #686. Just found it when creating a pull.

**Comment by hollasch** [comment] 2020-10-01 02:38
First! :D Thanks for reporting and offering to fix, though.

This will be included in v3.2.1 (from branch `dev-patch`), which I'm planning on releasing by this weekend.
