### ISSUE TITLE
[Question] perlin noise implementation

### ISSUE THREAD

**Issue by antoniogamiz** [RayTracing/raytracing.github.io#711] opened 2020-08-25 10:18 UTC
In the second book, in section 5.1, the `noise` method is implemented as follows:

~~~C++
        double noise(const point3& p) const {
            auto u = p.x() - floor(p.x());
            auto v = p.y() - floor(p.y());
            auto w = p.z() - floor(p.z());

            auto i = static_cast<int>(4*p.x()) & 255;
            auto j = static_cast<int>(4*p.y()) & 255;
            auto k = static_cast<int>(4*p.z()) & 255;

            return ranfloat[perm_x[i] ^ perm_y[j] ^ perm_z[k]];
        }
~~~

Why do they declare `u,v,w`, if they are unused? Maybe it should be as follows:

~~~C++
        double noise(const point3& p) const {
            auto u = p.x() - floor(p.x());
            auto v = p.y() - floor(p.y());
            auto w = p.z() - floor(p.z());

            auto i = static_cast<int>(4*u) & 255;
            auto j = static_cast<int>(4*v) & 255;
            auto k = static_cast<int>(4*w) & 255;

            return ranfloat[perm_x[i] ^ perm_y[j] ^ perm_z[k]];
        }
~~~

**Comment by antoniogamiz** [comment] 2020-08-25 10:43
Ah, they are used in the smoothing of the result. Maybe they should be removed from that part then.

**Comment by antoniogamiz** [comment] 2020-08-25 13:46
A direct link to the [blog post](http://eastfarthing.com/blog/2015-04-21-noise/) where Andrew Kensler explains how to build that perlin noise could be useful for readers interested in why that code is like that instead of copy-pasting.

**Comment by antoniogamiz** [comment] 2020-08-25 15:40
In addition, after reading the blog post and the section 5, I more or less understand Perlin noise implementation except for this line:
https://github.com/RayTracing/raytracing.github.io/blob/7b92650a045a887391bf8148af86c5e6c46c7a9e/src/common/perlin.h#L109

Andrew Kensler does not take that vector in his implementation, he does `dot(random_vector, point)`. Instead, we replace the point in the dot product with a different vector. Can someone explain to me why?

**Comment by hollasch** [comment] 2020-09-11 19:13
Duplicate of #684

**Closed by hollasch** 2020-09-11 19:13 UTC
