### ISSUE TITLE
[book 3][book1-review] Chapter 6 issues

### ISSUE THREAD

**Issue by genmeblog** [RayTracing/raytracing.github.io#1017] opened 2022-05-04 21:09 UTC
I go through The Rest of Your Life in version 4.x

First two images from Chapter 2.3 "Stratified Samples (Jittering)" created from my code are identical as in the book. The next changes are in Chapter 6.

Chapter 6.1 changes two things: `samples_per_pixel` are set to `100` (changed from `64`) and `scattering_pdf` is introduced (it doesn't matter in this chapter since `scattering_pdf/pdf = 1`. The Image 3 contains very low noise and from my experiments similar result can be achieved by setting `samples_per_pixel` to `1000` (not `100` as in the book).

Chapter 6.2 sets `pdf` to a constant, and again, Image 4 is far for the result I've got.

I know that images are going to be recreated - just wanted to emphasize it here.

Chapter 6.3 sets `scattering_pdf` to a constant, which with connection to a line from previous chapters (ie. `double pdf = scattering_pdf;`), again, gives ratio `scattering_pdf/pdf=1`. This degenerates to a hemisphere scattering from book1. 

Is it correct?

**Comment by hollasch** [comment] 2022-05-04 21:18
Will review.

**Comment by hollasch** [comment] 2024-03-27 02:06
This is two issues mixed together. First is dupe of #1018. Second is described in more detail in #1302.

**Closed by hollasch** 2024-03-27 02:06 UTC
Labels: book 3: Your Life
