### ISSUE TITLE
`near_zero()` contains magic epsilon number without giving any rational

### ISSUE THREAD

**Issue by MaliusArth** [RayTracing/raytracing.github.io#1665] opened 2024-12-21 12:37 UTC
Why is specifically 1e-8 chosen as the epsilon?
In the course of the books we are dealing with floating-point issues all the time, it would make sense to introduce the subject of epsilons and how to chose them sensibly (beyond just eyeballing or trial&erroring it).

**Comment by wwqwq2313** [comment] 2024-12-21 12:42
Hello, we tried to solve the issue.

This is what we did:

Added a detailed explanation of the epsilon value (1e-8) used in the near_zero() function. Included information on how to choose epsilon values sensibly for floating-point comparisons.

You can review changes in this commit: https://github.com/wwqwq2313/RayTracing-raytracing.github.io-1665/commit/54e436fc4e8e78abbdb5947d5e3e97d3156bc96b.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by hollasch** [comment] 2024-12-27 23:58
Duplicate of #329, #772, #979.

**Closed as not planned** 2024-12-27 23:59 UTC
Labels: resolved: duplicate
