### ISSUE TITLE
Typo at Book 1 sec2.1

### ISSUE THREAD

**Issue by zhuruisy** [RayTracing/raytracing.github.io#1264] opened 2023-09-13 05:30 UTC
147     green goes
148     from fully off at the top to black at the bottom. Adding red and green light together make

           should be 

          green goes
          from fully off at the top to fully green at the bottom. Adding red and green light together make

**Comment by hollasch** [comment] 2023-09-13 21:33
Duplicate of #1244.

**Closed as completed by hollasch** 2023-09-13 21:33 UTC
Labels: resolved: duplicate
