### ISSUE TITLE
[Book 2] Listing 13 : Undeclared variable "i" in for loop

### ISSUE THREAD

**Issue by manas96** [RayTracing/raytracing.github.io#459] opened 2020-04-08 14:38 UTC
In Listing 13 : 
```
for (const auto& object : objects) {
        if (!objects[i]->bounding_box(t0, t1, temp_box))
            return false;
        output_box = surrounding_box(output_box, temp_box);
    }
```
The variable `i` is not declared and unnecessary. It obviously should be using `object` instead of `objects[i]`.
I checked the code, this is fixed in hittable_list.h on master. Has not been updated in the book though.

**Comment by hollasch** [comment] 2020-04-08 16:38
Duplicate of #435.

**Closed by hollasch** 2020-04-08 16:38 UTC
