### ISSUE TITLE
Book One - Ray.h (Listing 7) #include folder confusion

### ISSUE THREAD

**Issue by dafhi** [RayTracing/raytracing.github.io#349] opened 2020-02-17 17:53 UTC
Dev.

"common" folder confusion

(Listing 7) .. "The ray class" includes "common/vec3.h" might be confusing for a total newb regarding continuity w/ Listing 6 .. "Creating a color gradient image"

(see previous issue:  newly-typed vec3.h)

**Comment by hollasch** [comment] 2020-02-22 11:08
Duplicate of #347

**Closed by hollasch** 2020-02-22 11:08 UTC
