### ISSUE TITLE
Book 2 Section 3.7 AABB surrounding box calculation incorrect for hollow glass sphere

### ISSUE THREAD

**Issue by digitalcarp** [RayTracing/raytracing.github.io#899] opened 2021-07-04 16:05 UTC
The AABB `surrounding_box()` function assumes that the min point is strictly less than the max point (i.e. x_min < x_max, y_min < y_max, z_min < z_max). However, the hollow glass sphere example from Book 1 Section 10.5 breaks this assumption by having a negative radius that flips the bounding box coordinates. This is a result of the `bounding_box()` calculation for spheres.

![Bad render of hollow sphere](https://user-images.githubusercontent.com/16604809/124391709-e42dc080-dcbf-11eb-9852-46291cc29238.png)

Consider a 1-D example with two bounding ranges (min, max) of (0, 10) and (-5, 5). If you flip one so that it is (10, 0) and (-5, 5), the `surrounding_box()` calculation gives the incorrect result (-5, 5). It should be (-5, 10).

A reasonable fix is to make the ordering assumption clear for `surrounding_box()` and update `bounding_box()` for `Sphere` and `MovingSphere`.

```
bool sphere::bounding_box(double time0, double time1, aabb& output_box) const {
    output_box = aabb(
        center - vec3(radius, radius, radius),
        center + vec3(radius, radius, radius));
    return true;
}
```
should probably be something like:
```
bool sphere::bounding_box(double time0, double time1, aabb& output_box) const {
    auto abs_r = abs(radius);
    auto vec_r = vec3(abs_r, abs_r, abs_r);
    output_box = aabb(
        center - vec_r
        center + vec_r);
    return true;
}
```
A similar approach would be taken for `MovingSphere`.

**Comment by hollasch** [comment] 2021-07-06 05:38
Duplicate of #532, fixed in `dev-major`.

**Closed by hollasch** 2021-07-06 05:38 UTC

**Comment by hollasch** [comment] 2021-07-06 19:37
By the way, without going through the pain of adopting a branch currently in development, your intermediate fix looks fine. I was going to suggest just adopting the new AABB, but the changes there are—of course—viral and extensive.

Thanks for reporting!
