### ISSUE TITLE
Book 1 Section 7.2 misspelled terminology

### ISSUE THREAD

**Issue by zentros** [RayTracing/raytracing.github.io#1113] opened 2023-05-10 17:06 UTC
### Book 1 Section 7.2 misspelled terminology :

_"Now's a good time to create a camera class to manage our virtual camera and the related tasks of scene **scampling**. The following class implements a simple camera using the axis-aligned camera from before:"_

The word "sampling" is misspelled as "scampling".

**Comment by hollasch** [comment] 2023-05-10 18:04
Duplicate of #921.

**Comment by hollasch** [comment] 2023-05-10 18:05
This is fixed in `dev-major`.

**Closed** 2023-05-10 18:05 UTC
