### ISSUE TITLE
[TheNextWeek] time1 and time2 versus time0 and time1

### ISSUE THREAD

**Issue by trevordblack** [RayTracing/raytracing.github.io#505] opened 2020-05-02 05:09 UTC
Similar to #418 
Present from 99 to line 645

We have differing variable names between the text and the src.

we sometimes have `time1` and `time2`, `time0` and `time1`, in the text.

And the associated source variable names are sometimes `time0` and `time1`, sometimes `tmin` and `tmax`, sometimes `t_min` and `t_max`

The text should match the source. All of these variables should also be standardized in the source. But that issue is #418

**Comment by hollasch** [comment] 2020-05-02 18:59
Closing this as a duplicate of #418. These should all be addressed cohesively in a single body of work.

**Closed by hollasch** 2020-05-02 18:59 UTC
