### ISSUE TITLE
AABB and BVH can not process a sphere containing a smaller sphere inside correctly.

### ISSUE THREAD

**Issue by SubjectNoi** [RayTracing/raytracing.github.io#1130] opened 2023-05-24 03:18 UTC
Hello, I'm new to ray tracing and now learning BVH and AABB. While I find that if I implement a bubble effect with:
```
sphere_material = make_shared<dielectric>(1.5);
world.add(make_shared<sphere>(center, -0.2 * 0.99, sphere_material));
world.add(make_shared<sphere>(center, 0.2, sphere_material));
```
The effect is as follows: 
![1111](https://github.com/RayTracing/raytracing.github.io/assets/23569127/e7c4be67-ecd1-4e30-b5b6-26ed60084f30)

While the BVH version gives me this

![2222](https://github.com/RayTracing/raytracing.github.io/assets/23569127/661e2ea2-34f7-420c-8622-8830af9db474)

and I guess this is because the AABB of inner sphere is completely contained by the AABB of outer sphere, but I wonder the exact reason and the solution to this.

Thanks!

**Comment by hollasch** [comment] 2023-05-24 19:04
I'm assuming that you're using the code from the `master` branch (the latest release). I wonder if the result is different if it's based on the new AABB and BVH code from the (in development) `dev-major` branch.

**Comment by SubjectNoi** [comment] 2023-05-27 22:50
Okay, I will try the code these days.

**Comment by SubjectNoi** [comment] 2023-05-30 05:32
I think I find the reason. If I change the minus radius of inner sphere to positive radius and use vanilla implementation without AABB and BVH, I get exactly the same effect with AABB and BVH version (with minus radius of inner sphere NOT changed to positive). So I guess there is something wrong with the front face setting in AABB and BVH implementation.

**Comment by trevordblack** [comment] 2023-06-19 21:45
This is a known problem with using the bubble hack on systems with BVHs.
There is a messy way to fix it that I'd rather not add to the books.
I'll loop back around on this.

**Comment by hollasch** [comment] 2023-06-19 21:46
I think it might be worthwhile to investigate this, but I believe we should kick this out of the v4.0.0 release.

**Comment by Imasu** [comment] 2024-02-22 00:23
Hello,

I appologize if my contribution is irrelevant as already addressed in Version 4.0.0-alpha.1, 2023-08-06, but when I implemented the AABB and BVH in c#, I needed to make a small change to the code to get the BvhNode.Hit method to work. Subsequently, when I attempted to reproduce the case, I obtained the expected result:

With a -0.9 sphere:
![image](https://github.com/RayTracing/raytracing.github.io/assets/4583573/fc70afb2-f47d-425a-be39-e7b01580b93e)

With a -1.1 sphere:
![image](https://github.com/RayTracing/raytracing.github.io/assets/4583573/c5e69d27-a140-4971-8957-ecc93a1e1dab)

My modification is straight forward : I create a new reference for the Interval to use in both left.hit & right.hit when the bBox.Hit condition is meet.
Without this adjustment, when the left.Hit check fails, the rayT interval is incorrectly updated with an inaccurate 'time' and the right.Hit is never triggered.

Below is my implementation of the method:

```
        public override bool Hit(Ray ray, Interval rayT, ref HitRecord hitRec) {
            if (!_bBox.AABBHit(ray, rayT))
                return false;

            bool hitLeft = _left.Hit(ray, new Interval(rayT.Min, rayT.Max), ref hitRec);
            bool hitRight = _right.Hit(ray, new Interval(rayT.Min, hitLeft ? hitRec.T : rayT.Max), ref hitRec);

            return hitLeft || hitRight;
        }
```

Since I haven't made any other changes (except for the comparison method), this approach may provide a solution to your issue.
I hope this helps!

**Comment by hollasch** [comment] 2024-03-20 23:48
It's possible that this is no longer an issue, since we've stopped using negative radius spheres. On the other hand, this might be a bug with smaller objects inside larger objects. Does this still reproduce with the new code?

**Comment by hollasch** [comment] 2024-04-09 03:52
I believe this is solved at this point as we've now disallowed negative radius spheres and instead model hollow transparent spheres with nested positive-radius spheres of outside-to-inside refractive indices. In any event, we can no longer try to reproduce this issue as negative radius spheres end up with a zero radius.

**Closed by hollasch** 2024-04-09 03:52 UTC
