### ISSUE TITLE
[Book 3, Chapter 3.7] Math error

### ISSUE THREAD

**Issue by dimitry-ishenko** [RayTracing/raytracing.github.io#1525] opened 2024-04-15 03:04 UTC
Just before Listing 15 we have:

> And we get the corresponding CDF:
> 
> $$ 𝑃(𝑟) = \frac {𝑟^3} 8 $$
> 
> and
> 
> $$ 𝑃^{−1}(𝑥) = 𝑓(𝑑) = 8 𝑑^{\frac 1 3} $$

The last formula seems to be incorrect and should be $𝑃^{−1}(𝑥) = 𝑓(𝑑) = \sqrt[3] {8 𝑑}$.

**Proof**: Earlier in the chapter we've defined function $f$ such that $f(P(r)) = r$.

Let's say $r = 1$. Then $P(1) = \frac {1^3} 8 = \frac 1 8$. If we use the original formula for $f$, we get:

$$ f(P(1)) = f(\frac 1 8) = 8 \cdot \sqrt[3] \frac 1 8 = 8 \cdot \frac 1 2 = 4 \neq 1 $$

With the new formula we get:

$$ f(P(1)) = f(\frac 1 8) = \sqrt[3]{8 \cdot \frac 1 8} = \sqrt[3] 1 = 1 $$

So, obviously, Listing 15 needs to be changed as well:

```diff
 double f(double d) {
-    return 8.0 * pow(d, 1.0/3.0);
+    return pow(8.0 * d, 1.0/3.0);
 }
```

**Comment by dimitry-ishenko** [comment] 2024-04-15 05:23
The formula also needs to be fixed in the 3rd paragraph below Listing 15:

> In all of the examples given, we always converged to the correct answer of 8/3. We got the same answer when we used both a uniform PDF and the “correct” PDF (i.e. $𝑓(𝑑) = 8 𝑑^{\frac 1 3}$). ...

**Comment by hollasch** [comment] 2024-04-15 20:05
Duplicate of #1310

**Closed as completed** 2024-04-15 20:05 UTC
Labels: resolved: duplicate
