### ISSUE TITLE
[Book 1] Possible typo in 2.1

### ISSUE THREAD

**Issue by AndyJLi0** [RayTracing/raytracing.github.io#1284] opened 2023-09-27 19:53 UTC
In the first book, the last paragraph of 2.1 says 

"Red goes from fully off (black) to fully on (bright red) from left to right, and green goes from fully off at the top to **black** at the bottom. Adding red and green light together make yellow so we should expect the bottom right corner to be yellow."

Shouldn't it be **green** instead? not black?

**Comment by armansito** [comment] 2023-09-27 20:25
Thank you for the report. This is a duplicate of #1244

**Closed as completed by armansito** 2023-09-27 20:25 UTC
Labels: resolved: duplicate
