### ISSUE TITLE
[Book 3] Section 12.2's `ray` construction is missing the `time` parameter

### ISSUE THREAD

**Issue by define-private-public** [RayTracing/raytracing.github.io#737] opened 2020-09-30 01:32 UTC
This line:

```c++
srec.specular_ray = ray(rec.p, reflected+fuzz*random_in_unit_sphere());
```

It should take in a time argument.

**Comment by hollasch** [comment] 2020-09-30 19:36
Duplicate of #133

**Closed by hollasch** 2020-09-30 19:36 UTC
