### ISSUE TITLE
Book 1: Image 8 contains incorrect rendering after Section 8.3 

### ISSUE THREAD

**Issue by ronnieholm** [RayTracing/raytracing.github.io#875] opened 2021-03-21 21:59 UTC
The image rendered at the end of Section 8.3 appears to be the result of fixing shadow acne in Section 8.4, and should probably be placed at the end of Section 8.4.

Placing the image after Section 8.3 causes one to go hunt through the code for bugs because the image is too dark.

**Comment by hollasch** [comment] 2021-03-22 01:36
We'll double check this during the v4.0.0 sanity pass.

**Comment by johannmeyer** [comment] 2021-04-23 12:30
I am unable to reproduce image 7 in sec 8.21(The first render of a diffuse sphere) and image 8 in sec 8.22 (gamma correction). My images are much darker than the images shown but removing the shadow acne by setting `t_min = 1e-3` corrects it mostly but the produced images are then lighter than image 7 or 8. Image 9 is reproducible though.

**Comment by luizfnetto** [comment] 2021-05-30 17:54
> The image rendered at the end of Section 8.3 appears to be the result of fixing shadow acne in Section 8.4, and should probably be placed at the end of Section 8.4.
> 
> Placing the image after Section 8.3 causes one to go hunt through the code for bugs because the image is too dark.

Thanks for your comment. It solved for me. I began to bug hunt and came here before doing a thorough check.

**Comment by hollasch** [comment] 2021-05-31 21:48
Thank you for the additional information!

**Comment by webanck** [comment] 2021-09-04 20:42
I concur, image 8 (section 8.3) is much closer to the result I get after taking care of shadow acne (section 8.4), even with the gamma correction.

**Comment by ISchenhaiqing** [comment] 2022-01-16 09:41
I fix this bug.
```
if (root < t_min || t_max < root) {
        root = (-half_b + sqrtd) / a;
        if (root < t_min || t_max < root)
            return false;
    }
```
**[sphere.h] Ray-sphere intersection code (now)**

```
if (root <= t_min || t_max <= root) {
        root = (-half_b + sqrtd) / a;
        if (root <= t_min || t_max <= root)
            return false;
    }
```
**[sphere.h] Ray-sphere intersection code (after fixing)**
The inconsistency between the 2020 version and the 2016 version results in a different energy transfer that makes the current result darker than the previous one.

**Comment by tysonliddell** [comment] 2023-03-13 00:38
Confirming @ISchenhaiqing's fix yields an image that seems to match Image 7 in the book much more closely.

#### Before the fix
![before_fix](https://user-images.githubusercontent.com/20079016/224584259-89160f2c-a221-4381-896c-a9bd4d7d7d18.jpg)

#### After the fix
![after_fix](https://user-images.githubusercontent.com/20079016/224584274-fa554758-e3df-4526-bfc5-63308c192a6f.jpg)

**Comment by samuel-cavalcanti** [comment] 2023-04-30 14:21
@hollasch , is the darker sphere the correct one ? 

my rendered diffuse sphere         |   Image 7: First render of a diffuse sphere
:-------------------------:|:---------:
![diffuse_material](https://user-images.githubusercontent.com/24573157/235358001-d575a0ca-d53b-4fbb-b94d-7a5a69c71bc2.png)|  ![antialiasing](https://raytracing.github.io/images/img-1.07-first-diffuse.png)

**Comment by hollasch** [comment] 2023-05-01 03:29
I believe the right image is the correct one.

**Comment by hollasch** [comment] 2023-05-11 03:56
The latest code in the `dev-major` branch looks like this:

```
if (!ray_t.contains(root)) {
    root = (-half_b + sqrtd) / a;
    if (!ray_t.contains(root))
        return false;
}
```

This uses the new `interval::contains()` method, which internally returns true for points on the closed interval. This means that the negation tests for points outside the open interval, yielding the dark image above ( _think_; I haven't verified this).

For the time being, I'll make the test more explicit instead of relying on the definition of `interval::contains()` method. This should correct the code in the `dev-major` branch, but I'll leave this issue open, to be fully verified with the `v4.0.0-release` milestone that goes through and regenerates all images one-by-one.

**Comment by hollasch** [comment] 2023-05-11 19:46
Brilliant! I really like the `inside` naming. I thought of `close-contains` and `open-contains`, which are _horrible_. I prefer `!contains` instead of `outside`, as it's simpler and means API surface. I'll make these changes and we'll see how it looks.

**Comment by hollasch** [comment] 2023-05-11 20:15
Ugh. `inside` reverses the meaning. For example, `ray_t.contains(x)` makes sense, but `ray_t.inside(x)` is misleading. Thinking...

- `surrounds`
- `encloses`
- `envelops`

I think I'll go with `surrounds`.

**Comment by hollasch** [comment] 2023-05-11 20:21
Another random thought: `bool inside (interval, double)` and `bool on (interval, double)`. I like this approach less, though.

**Closed** 2023-07-26 22:37 UTC
