### ISSUE TITLE
Book 1 Image 19 / Listing 75 mistmatch.

### ISSUE THREAD

**Issue by KnockerPulsar** [RayTracing/raytracing.github.io#1101] opened 2023-01-07 13:15 UTC
Hello, I was going through the dev-major version of the book and noticed that the code in listing 75 specifies the inverted dielectric sphere to be of radius `-0.4`, while the image seems to show one of radius `-0.45`.

Current version of image 19:
![image](https://user-images.githubusercontent.com/12754772/211152345-358a219e-3a29-451a-b53d-be4f17f0ca10.png)

My version of image 19 with radius `-0.4`:
![image](https://user-images.githubusercontent.com/12754772/211152397-3dc9b04d-e125-4ac1-b3d9-82912f128ef7.png)

My version of image 19 with radius `-0.45`:
![image](https://user-images.githubusercontent.com/12754772/211152427-78518047-0353-4cb4-82eb-ecd93417d1bf.png)

**Comment by hollasch** [comment] 2023-01-08 11:32
Duplicate of #978.

**Closed by hollasch** 2023-01-08 11:32 UTC
