### ISSUE TITLE
Isuse about checker texture

### ISSUE THREAD

**Issue by YohnWang** [RayTracing/raytracing.github.io#818] opened 2020-12-03 13:07 UTC
in texture.h,the book gives 
```c++
virtual color value(double u, double v, const point3& p) const override {
            auto sines = sin(10*p.x())*sin(10*p.y())*sin(10*p.z());
            ...
```
but this code will get strange checker texture in plane while plane is not aligned axis,should we change to
```c++
            auto sines = sin(u)*sin(v);
```
however,the u,v should do more details to suit this change.
Thank you!

**Comment by trevordblack** [comment] 2020-12-03 18:30
This is a duplicate of #663 

Closing.

**Closed** 2020-12-03 18:30 UTC
