### ISSUE TITLE
Book 1 Section 2.2 encoding issue

### ISSUE THREAD

**Issue by htwong737** [RayTracing/raytracing.github.io#886] opened 2021-04-15 06:15 UTC
Recommend to remind the people if they use the powershell which win10 has given during installing, the output image file then will be encoded as UTF-16 LE, which will cause mostly image viewers which claims to be able to open ppm file then cannot open it.
There are two resolutions.
1. Use cmd
2. Use the newest powershell 
These two terminal will let the file be encoded as UTF-8, and it can be opened and seen normally.

**Comment by hollasch** [comment] 2021-10-21 00:00
Duplicate of #636

**Closed by hollasch** 2021-10-21 00:00 UTC
