### ISSUE TITLE
ch05, include float.h header file

### ISSUE THREAD

**Issue by Joeycho** [RayTracing/raytracing.github.io#161] opened 2019-09-01 11:52 UTC
Hello, I keep following the code, even though some parts are still not clear for me,

In the code, I wonder why there is float.h file.

If that is only for `MAXFLOAT` constant, then my suggestion is...

`#include <cfloat>`, and using `FLT_MAX` rather than `MAXFLOAT`.

What do you think? 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ C++
    #include <iostream>
    #include "sphere.h"
    #include "hitable_list.h"
    #include "float.h"  // THIS PART

    vec3 color(const ray& r, hitable *world) {
        hit_record rec;
        if (world->hit(r, 0.0, MAXFLOAT, rec)) { //<< Indicator for MAXFLOAT
            return 0.5*vec3(rec.normal.x()+1, rec.normal.y()+1, rec.normal.z()+1);
        }
        else {
            vec3 unit_direction = unit_vector(r.direction());
            float t = 0.5*(unit_direction.y() + 1.0);
            return (1.0-t)*vec3(1.0, 1.0, 1.0) + t*vec3(0.5, 0.7, 1.0);
        }
    }

    int main() {
        int nx = 200;
        int ny = 100;
        std::cout << "P3\n" << nx << " " << ny << "\n255\n";
        vec3 lower_left_corner(-2.0, -1.0, -1.0);
        vec3 horizontal(4.0, 0.0, 0.0);
        vec3 vertical(0.0, 2.0, 0.0);
        vec3 origin(0.0, 0.0, 0.0);
        hitable *list[2];
        list[0] = new sphere(vec3(0,0,-1), 0.5);
        list[1] = new sphere(vec3(0,-100.5,-1), 100);
        hitable *world = new hitable_list(list,2);
        for (int j = ny-1; j >= 0; j--) {
            for (int i = 0; i < nx; i++) {
                float u = float(i) / float(nx);
                float v = float(j) / float(ny);
                ray r(origin, lower_left_corner + u*horizontal + v*vertical);

                vec3 p = r.point_at_parameter(2.0);
                vec3 col = color(r, world);
                int ir = int(255.99*col[0]);
                int ig = int(255.99*col[1]);
                int ib = int(255.99*col[2]);

                std::cout << ir << " " << ig << " " << ib << "\n";
            }
        }
    }
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`

**Comment by hollasch** [comment] 2019-09-06 22:14
Closing as duplicate of #19

**Closed by hollasch** 2019-09-06 22:14 UTC
