### ISSUE TITLE
Add a comment to hint at a HitRecord's change

### ISSUE THREAD

**Issue by MacGamerFR** [RayTracing/raytracing.github.io#528] opened 2020-05-11 14:30 UTC
In the `The next Week` book, after the ConstantTexture defintion, in the Listing 20, we are using rec.u and rec.v, that have not been introduced.

**Comment by hollasch** [comment] 2020-05-11 18:51
Duplicate of #496, fixed in dev-minor for v3.2.0 release.

**Closed by hollasch** 2020-05-11 18:51 UTC
